export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#baa3ff",
        "surface-tint": "#4a40e0",
        "primary-fixed-dim": "#8885ff",
        "error-container": "#f74b6d",
        "tertiary-container": "#baa3ff",
        "tertiary-dim": "#583ba5",
        "error-dim": "#a70138",
        "on-primary-fixed": "#000000",
        "on-tertiary-fixed-variant": "#41208e",
        "on-secondary-container": "#2f2ebf",
        "surface-container-low": "#ecf1f6",
        "on-secondary": "#f4f1ff",
        "primary-dim": "#3d30d4",
        "outline-variant": "#a9aeb1",
        "secondary": "#4647d3",
        "on-error": "#ffefef",
        "tertiary-fixed-dim": "#ad92ff",
        "surface-container-high": "#dde3e8",
        "tertiary": "#6448b2",
        "primary": "#4a40e0",
        "outline": "#73777b",
        "error": "#b41340",
        "background": "#f3f7fb",
        "surface-container-highest": "#d7dee3",
        "secondary-dim": "#3939c7",
        "on-tertiary": "#f7f0ff",
        "on-tertiary-fixed": "#1d0054",
        "surface-container": "#e3e9ee",
        "on-error-container": "#510017",
        "secondary-fixed": "#cdcdff",
        "secondary-container": "#cdcdff",
        "on-surface": "#2a2f32",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#381485",
        "surface-variant": "#d7dee3",
        "secondary-fixed-dim": "#bdbeff",
        "primary-fixed": "#9795ff",
        "on-secondary-fixed-variant": "#3a3ac8",
        "on-primary-container": "#14007e",
        "surface-bright": "#f3f7fb",
        "primary-container": "#9795ff",
        "on-surface-variant": "#575c60",
        "inverse-on-surface": "#999da1",
        "on-secondary-fixed": "#160bae",
        "on-primary-fixed-variant": "#1a0099",
        "on-background": "#2a2f32",
        "inverse-primary": "#8582ff",
        "on-primary": "#f4f1ff",
        "inverse-surface": "#0a0f12",
        "surface": "#f3f7fb",
        "surface-dim": "#ced5db"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
